name: safe_circle
description: An app that helps you to stay within your 5km excercise limit.
publish_to: 'none'
version: 1.0.8+10
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.1
  provider: ^4.3.3
  flutter_local_notifications: ^1.4.2
  cupertino_icons: ^1.0.0
  background_location: ^0.4.0
  flutter_launcher_icons: ^0.8.1
  flutter_spinkit: ^4.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  image_path: 'assets/launcher/icon.png'
  android: true
  ios: true